name: base
channels:
  - conda-forge
  - defaults
  - r
dependencies:
  - cmake
  - r-arrow
  - r-duckdb
  - r-rjava
  - openssl
  - jupyter-server-proxy
  - websockify
  - pip:
    - jupyter-rsession-proxy