name: Image Variant Manifest

on:
  workflow_dispatch:

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
        pat_token: ${{ steps.set_pat_token.outputs.pat_token }}
    steps:
        - name: Set GH PAT Token
          id: set_pat_token 
          env:
            PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          run: | 
            echo "pat_token=$PAT_TOKEN" >> $GITHUB_OUTPUT

  darwin:
    needs: [config]
    uses: lsc-sde/lsc-sde/.github/workflows/docker-build.yaml@mph/integrate-omop
    with:
        imageName: datascience-jupyter-omop
        platforms: '[ "amd64" ]'
        tag: '1.0.1'
        targets: '[ "darwin" ]'
        buildArgs: '[{
         "TARGET_VERSION": "v1",
         "DARWIN_BUILD_VERSION": "v1.4.1",
         "PAT_TOKEN": "${{ needs.config.outputs.pat_token }}"
         }]'
    secrets: inherit