name: Image Variant Manifest

on:
  workflow_dispatch:

jobs:
  darwin:
    uses: lsc-sde/lsc-sde/.github/workflows/docker-release.yaml@main #lsc-sde/lsc-sde/.github/workflows/docker-build.yaml@mph/integrate-omop
    with:
        imageName: datascience-jupyter-omop
        platforms: '[ "amd64" ]'
        targets: '[ "darwin" ]'
        buildArgs: '[{
            "TARGET_VERSION": "v1",
            "DARWIN_BUILD_VERSION": "v1.4.0"
         }]'
        runnerType: 8x-linux-x64
    secrets: inherit