name: Image Variant Manifest
on:
    #push:
    workflow_dispatch:
jobs:
    base:
        uses: lsc-sde/lsc-sde/.github/workflows/docker-build.yaml@mph/integrate-omop
        with:
            imageName: datascience-jupyter-omop
            platforms: '[ "amd64" ]' #"arm64", 
            tag: '1.0.1'
            targets: '[ "darwin" ]'
            buildArgs: '[{
                            "TARGET_VERSION": "v1",
                            "DARWIN_BUILD_VERSION": "v1.4.1",
                            "PAT_TOKEN":"${{ secrets.PAT_TOKEN }}"
                        }]'

        secrets: inherit

    # darwin:
    #     uses: lsc-sde/lsc-sde/.github/workflows/docker-release.yaml@mph/integrate-omop
    #     with:
    #         imageName: datascience-jupyter-omop
    #         directory: docker/datascience-jupyter-omop
    #         platforms: '[ "amd64" ]'
    #         tagPrefix: darwin
    #         buildArgs: '[{
    #                         "VARIANT": "darwin",
    #                         "VERSION": "v1.4.0",
    #                         "PLATFORM": "amd64"
    #                     }]'
    #     secrets: inherit