name: Image Variant Manifest
on:
    #push:
    workflow_dispatch:
jobs:
    base:
        uses: lsc-sde/lsc-sde/.github/workflows/docker-build.yaml@mph/integrate-omop   #just call docker-build.yaml
        with:
            imageName: datascience-jupyter-omop
            platforms: '[ "amd64" ]' #"arm64", 
            tag: 'v1'
            targets: '[ "base" ]'
            buildArgs: '[{
                            "VERSION": "v1"
                        }]'

        secrets: inherit
    # darwin:
    #     uses: lsc-sde/lsc-sde/.github/workflows/docker-release.yaml@mph/integrate-omop
    #     with:
    #         imageName: datascience-jupyter-omop
    #         directory: docker/datascience-jupyter-omop
    #         platforms: '[ "amd64" ]'
    #         tagPrefix: darwin
    #         buildArgs: '[{
    #                         "VARIANT": "darwin",
    #                         "VERSION": "v1.4.0",
    #                         "PLATFORM": "amd64"
    #                     }]'
    #     secrets: inherit